import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { DatabaseSync } from "node:sqlite";
test("migration preserves menu content and reseeding cannot resurrect deleted dishes", () => {
  const directory = mkdtempSync(join(tmpdir(), "angel-menu-test-"));
  const env = { ...process.env, DATABASE_URL: "", LOCAL_DATABASE_PATH: join(directory, "test.sqlite"), NODE_ENV: "test" as const, VERCEL: "" };
  const run = (mode: string) => { const result = spawnSync(process.execPath, ["scripts/database.mts", mode], { env, encoding: "utf8" }); assert.equal(result.status, 0, result.stderr); };
  run("migrate"); run("migrate"); run("seed"); run("verify");
  const db = new DatabaseSync(env.LOCAL_DATABASE_PATH);
  db.exec("PRAGMA foreign_keys=ON");
  const snapshot = JSON.parse(readFileSync("db/original-menu.json", "utf8"));
  const total = snapshot.menu.reduce((sum: number, category: { items: unknown[] }) => sum+category.items.length, 0);
  assert.equal(db.prepare("SELECT count(*) AS total FROM menu_items").get()?.total, total);
  assert.throws(() => db.prepare("UPDATE menu_items SET price_cents=-1").run());
  assert.throws(() => db.prepare("UPDATE menu_items SET category_id='missing'").run());
  assert.throws(() => db.prepare("UPDATE menu_items SET image='' WHERE type='chef-special'").run());
  db.exec("DELETE FROM menu_items WHERE id=(SELECT id FROM menu_items LIMIT 1)");
  run("seed");
  assert.equal(db.prepare("SELECT count(*) AS total FROM menu_items").get()?.total, total-1);
  db.close();
});
